Edenbridge2/urls.py
from django.contrib import admin
from django.urls import include, path
import info.views
from register import views as v
from register.views import Passwordviewss
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("info.urls")),
    path('', include("schedule.urls")),
    path('', include("booktime.urls")),
    path('', include("django.contrib.auth.urls")),
    path("addstaff", v.register, name="register"),
    path("changepass/", Passwordviewss.as_view(template_name='info/Staff/changepass.html'), name="register"),
    path("modstaff/<str:pk_test>/", v.modstaff, name="modstaff"),
]

info/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
import register.views
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('land', views.land, name='land'),
    path('land/coordinator', views.cor, name='land-cor'),
    path('land/worker', views.wok, name='land-wok'),
    path('land/bookeeper', views.bok, name='land-bok'),
    path('help', views.help1, name='help'),
    path('about', views.about, name='about'),
    path('viewstaff', views.viewstaff, name='viewstaff'),
    path('addclient', views.addclient, name='addclient'),
    path('viewclient', views.viewclient, name='viewclient'),
    path('modclient/<str:pk_test>/', views.modclient, name='modclient'),
    path('adddep', views.adddep, name='adddep'),
    path('viewdep', views.viewdep, name='viewdep'),
    path('moddep/<str:pk_test>/', views.moddep, name='moddep'),
    path('passuser/<str:pk_test>/', views.changeuserpass, name='passuser'),

]

schedule/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [

    path('scheduleshift', views.scedshift, name='schedshift'),
    path('viewshift', views.viewshift, name='viweshift'),
    path('viewrecshift', views.viewrecshifts, name='viwerecshift'),
    path('modshift/<str:pk_test>/', views.modshift, name='modshift'),
    path('modrecshift/<str:pk_test>/', views.modrecshift, name='modrecshift'),
    path('approvehours', views.approvehours, name='approvehours'),
    path('approve/<str:pk_test>/', views.approve, name='approve'),
    path('reports', views.reports, name='reports'),



]

schedule/models.py
from django.db import models

# Create your models here.

schedule/forms.py
from django import forms


class scedshiftform(forms.Form):
    client_id = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    dep_code = forms.CharField(required=True)
    rec_shift = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'onchange': 'myFunction()'}))
    shift_date = forms.DateField(required=True, widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))
    scheduled_start = forms.TimeField(required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'time'}))
    scheduled_end = forms.TimeField(required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'time'}))
    staff_id = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    shift_super = forms.BooleanField(required=False)
    shift_notes = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control'}))

schedule/views.py
import datetime
import django.utils.datastructures
from .forms import scedshiftform
from django.contrib.auth.decorators import login_required
import json
from info.decorators import allowed_users, allowed_users1
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.db.models import Max
from .function_roll import *


# Create your views here.

# Makes sure the users auth lvl is to the required lvl.
@login_required
@allowed_users(allowed_roles=['Coordinator', 'Bookeeper'])
def scedshift(request):
    user_group = request.user.groups.values_list('name', flat=True)
    user_group = str(user_group[0])

    # Defined variables.
    getdep = Department.objects.all()
    dropdown_varibles = Client.objects.all().values_list('client_id', 'client_fname', 'client_lname')
    dropdown_varibles1 = Profile.objects.all()
    dropdown_varibles2 = Profile.objects.filter(type_code='Worker').values_list('staff_id', 'staff_fname', 'staff_lname')
    dropdown = ['Error'] * len(dropdown_varibles)
    dropdownst = ['Error'] * len(dropdown_varibles2)
    counter = 0
    counter2 = 0
    error = 0
    shiftdatae = ''
    shiftstart = ''
    shiftend = ''
    cliid = ''
    today = date.today()
    recshift = ''
    supernum = ''
    shiftnotes = ''
    depart = ''
    avalablestaff = ''
    # Making a dropdown with all clients
    for i in dropdown_varibles:
        dropdown[counter] = 'CID(' + str(i[0]) + ')' + ' ' + i[1] + ', ' + i[2]
        counter += 1
    dropdown = json.dumps(list(dropdown))
    for i in dropdown_varibles2:
        dropdownst[counter2] = 'ID(' + str(i[0]) + ')' + ' ' + i[1] + ', ' + i[2]
        counter2 += 1
    dropdown2 = json.dumps(list(dropdownst))
    if request.method == "POST":
        form = scedshiftform(request.POST)
        # If the user presses the button to find avalible staff this route is used.
        if 'getstaff' in request.POST['submit']:
            if form:
                # setting variables to avoid errors.
                dateerror = 0
                starterror = 0
                enderror = 0
                shiftdatae = ''
                shiftstart = ''
                shiftend = ''
                form.full_clean()
                recshift = form.cleaned_data["rec_shift"]
                supernum = form.cleaned_data["shift_super"]
                # The form is not verified due to this search requiring only 3 variables, Another form cloud be created
                # but this is quicker and will return fewer errors. These trys make sure the variables are set and
                # returns an error if not.
                try:
                    clientname = str(form.cleaned_data["client_id"])
                except KeyError:
                    clientname = ''
                try:
                    shiftnotes = form.cleaned_data["shift_notes"]
                except KeyError:
                    shiftnotes = ""
                try:
                    depart = form.cleaned_data["dep_code"]
                except KeyError:
                    depart = ""
                try:
                    cliid = form.cleaned_data["client_id"]
                except KeyError:
                    cliid = ""
                try:
                    shiftdatae = form.cleaned_data["shift_date"]
                    shiftdate = str(shiftdatae).split("-")
                except KeyError as e:
                    error += 1
                    dateerror = 1
                try:
                    shiftstart = form.cleaned_data["scheduled_start"]
                except KeyError as e:
                    error += 1
                    starterror = 1
                try:
                    shiftend = form.cleaned_data["scheduled_end"]
                except KeyError as e:
                    error += 1
                    enderror = 1
                # If there is an error a message is returned.
                if error > 0:
                    if dateerror == 1:
                        shiftdatae = ''
                    if starterror == 1:
                        shiftstart = ''
                    if enderror == 1:
                        shiftend = ''
                    form = scedshiftform(initial={'shift_date': shiftdatae, 'scheduled_start': shiftstart,
                                                  'scheduled_end': shiftend, 'client_id': clientname,
                                                  'rec_shift': recshift,
                                                  'shift_super': supernum, 'shift_notes': shiftnotes})
                    # This gets the department and returns nothing if nothing was set.
                    try:
                        quryval = Department.objects.filter(dep_code=depart).values_list('dep_name', flat=True)
                        progval = 'value=' + str(depart)
                        progval1 = str(quryval[0])
                    except IndexError:
                        progval = 'value='
                        progval1 = 'Select a Department:'
                    messages.warning(request, 'Make sure the Date, start time, and end time are filled out ',
                                     extra_tags='mor')
                    return render(request, 'schedule/schedshift.html',
                                  {'staffis': 1, 'form': form, 'dep': getdep, 'dropdown': dropdown,
                                   'dropdown1': dropdown_varibles1,
                                   'state': False, 'startval': progval, 'startval1': progval1, 'dropdown2': dropdown2, 'usertype': user_group})
                shiftday = datetime(int(shiftdate[0]), int(shiftdate[1]), int(shiftdate[2])).weekday()
                dayofweek = {0: 'mon_avail', 1: 'tue_avail', 2: 'wed_avail', 3: 'thu_avail', 4: 'fri_avail',
                             5: 'sat_avail', 6: 'sun_avail', }
                query = getdayofweek(shiftday)
                stafflist = query.values_list(dayofweek[shiftday], 'staff_id', 'staff_fname', 'staff_lname')
                count = 0
                # This finds avalible staff based on time and date
                avalablestaff = [''] * len(stafflist)
                for i in stafflist:
                    timelist = str(i[0]).split(' - ')
                    start = str(timelist[0]).split(':')
                    start = datetime.time(int(start[0]), int(start[1]))
                    end = str(timelist[1]).split(':')
                    end = datetime.time(int(end[0]), int(end[1]))
                    if shiftstart.hour <= start.hour and shiftend.hour >= end.hour:
                        avalablestaff[count] = [i[1], i[2], i[3]]
                        count += 1
            form = scedshiftform(initial={'shift_date': shiftdatae, 'scheduled_start': shiftstart,
                                          'scheduled_end': shiftend, 'client_id': cliid, 'rec_shift': recshift,
                                          'shift_super': supernum, 'shift_notes': shiftnotes})
            deparmenv = getdepartment(depart)
            # This will return an error message if there are no staff with the required specs.
            if not avalablestaff:
                messages.warning(request, 'No avalable staff for the given date/time', extra_tags='mor')
            return render(request, 'schedule/schedshift.html',
                          {'staffis': 0, 'form': form, 'dep': getdep, 'dropdown': dropdown, 'dropdown1': avalablestaff,
                           'state': False, 'startval1': deparmenv[1], 'startval': deparmenv[0], 'dropdown2': dropdown2, 'usertype': user_group})
        # If the user presses submit this route is taken.
        if 'make' or 'make1' in request.POST['submit']:
            if form.is_valid():
                form.full_clean()
                # Declaring variables and reworking data into differant forms.
                clientname = str(form.cleaned_data["client_id"])
                cleaned = str(form.cleaned_data["client_id"]).split(' ')
                cleaned = cleaned[0].replace('CID(', '').replace(')', '')
                staffnum = form.cleaned_data["staff_id"]
                cleanedstaff = str(form.cleaned_data["staff_id"]).split(' ')
                staffid = cleanedstaff[0].replace('ID(', '').replace(')', '')
                recshift = form.cleaned_data["rec_shift"]
                supernum = form.cleaned_data["shift_super"]
                shiftnotes = form.cleaned_data["shift_notes"]
                clendepart = form.cleaned_data["dep_code"]
                depart = Department.objects.get(dep_code=form.cleaned_data["dep_code"])
                cliid = Client.objects.get(client_id=cleaned)
                shiftdatae = form.cleaned_data["shift_date"]
                shiftstart = form.cleaned_data["scheduled_start"]
                shiftend = form.cleaned_data["scheduled_end"]
                staff = Profile.objects.get(staff_id=staffid)
                # See function_roll.py for erroring the inputs
                print(today)
                print(request.POST['shift_date'])
                if request.POST['shift_date'] < str(today):
                    form = scedshiftform(initial={'shift_date': shiftdatae, 'scheduled_start': shiftstart,
                                                  'scheduled_end': shiftend, 'client_id': clientname,
                                                  'rec_shift': recshift,
                                                  'shift_super': supernum, 'shift_notes': shiftnotes})
                    deparmenv = getdepartment(clendepart)
                    staffreturn = getstaff(staffid)
                    messages.warning(request, 'The start date must be after the current date.',
                                     extra_tags='error')
                    return render(request, "schedule/schedshift.html",
                                  {'staffis': 1, 'form': form, 'dep': getdep, 'dropdown': dropdown,

templates/schedule/modrecshift.html
{% extends "info/base.html" %}

{% block title %}
Mod Recurring Shift
{% endblock %}

{% block content %}
    {% if usertype == 'Bookeeper' %}
        {% include 'info/includes/book_navbar.html' %}
    {% else %}
        {% include 'info/includes/corr_navbar.html' %}
    {% endif %}
                {% load static %}
       <link rel="stylesheet" href="{% static 'jquery-ui.css' %}" />

      <script src="{% static 'js/jquery-3.6.0.js' %}" ></script>
  <script  src="{% static 'js/jquery-ui-1.13.1.js' %}" ></script>
 <script>
 function changestaff(){
     let words = "";
     words = document.getElementById('staff_search').value;
     let array = words.split(" ");
     let final = array[0].replace(/[()ID]/g,"");
     document.getElementById('id_staff_id').value = final
 }
 </script>
  <script>
  $( function() {
    let availableTags = {{ dropdown | safe }};
    $( "#id_client_id" ).autocomplete({
      source: availableTags
    });
  } );
  </script>
  <script>
  $( function() {
    let availableTags1 = {{ dropdown2 | safe }};
    $( "#staff_search" ).autocomplete({
      source: availableTags1
    });
  } );
  </script>


<!,
      change: function (event, ui) {
          document.getElementById('id_staff_id').value=13;
      }>

<div class='conb'><div class='row justify-content-md-center'><br />




				<form class='form-con' method="post">
                {% csrf_token %}





				<h1>Modify a recurring shift</h1>
                    {% for message in messages %}

    {% if 'error' in message.extra_tags %}
        <div class='alert alert-danger'>{{ message }}</div>
    {% elif 'submit' in message.extra_tags %}
        <div class='alert alert-success'>{{ message }}</div>
    {% endif %}

{% endfor %}
                    {% if overtime == 1 %}
                        <p style="color: orangered">Press the Schedule button to schedule overtime shifts</p>
                        <button name="submit" class='btn btn-primary' type="submit" value="make1">Schedule</button>
                    {% endif %}
                <br>


				 <form class='form-con' method="post">

                    <label>Recurring day: {{ day }}</label><br><br>

					<label>Search for Clients:</label>
						{{ form.client_id.errors }}{{ form.client_id }}<br /><br />

					<!--display selection of clients-->


					<!--display selection of departments-->
					Department:
						<select class='fanc' name='dep_code' id="id_dep_code" required="" type="text" class="form-control">
							<option hidden {{ startval }}>{{ startval1 }}</option>
						{% for o in dep %}
                            <option value ="{{ o.dep_code }}">{{ o.dep_name }}</option><br /><br />
                        {% endfor %}
						</select><br /><br />


					Start Time:<div class='form-row'><div class='col-12'>
						{{ form.scheduled_start.errors }}{{ form.scheduled_start }}<br /><br />

					</div></div>End Time:<div class='form-row'><div class='col-12'>
						{{ form.scheduled_end.errors }}{{ form.scheduled_end }}<br /><br />

					<!--button to find available staff-->
					</div></div><button formnovalidate name="submit" class='btn btn-primary' type="submit" value="getstaff">View Available Staff</button><br /><br />


                    {% for message in messages %}

    {% if 'mor' in message.extra_tags %}
        <div class='alert alert-danger'>{{ message }}</div>
    {% endif %}

{% endfor %}

					Search for Staff:
                    <input class='form-control' name='staff_search' id='staff_search' onfocus="this.value=''" type="text">
                 <button class="form-control" type="button" onclick="changestaff()">Set staff</button><br /><br />

					<!--display selection of staff members-->
					Staff results:
						<select class='fanc' name='staff_id' id='id_staff_id' type="text" onchange="document.getElementById('staff_search').value = ''" required="">
                            <option hidden {{ staffval }}>{{ staffval1 }}</option>
                            {% for o in dropdown1 %}
                                {% if staffis == 1 %}
                                    <option value ="{{ o.staff_id }}">ID({{ o.staff_id }}) {{ o.staff_fname }}, {{ o.staff_lname }}</option><br /><br />
                                {% else %}
                                    <option value ="{{ o.0 }}">ID({{ o.0 }}) {{ o.1 }}, {{ o.2 }}</option>
                                {% endif %}
                        {% endfor %}
						</select><br /><br />

						is a supervisor:
                    {% if super == 1 %}
					    <input type="checkbox" name="shift_super" value="1" id="id_shift_super" checked=""><br /><br />
                    {% else %}
                         <input type="checkbox" name="shift_super" value="0" id="id_shift_super" unchecked=""><br /><br />
                    {% endif %}
					Shift Notes:<br />
						{{ form.shift_notes.errors }}{{ form.shift_notes }}<br /><br />

					<button name="submit" class='btn btn-primary' type="submit" value="make">Submit</button>
					<a href='/viewrecshift' class='btn btn-danger'>Cancel</a>

                 </div></form><br />



		</form>
            </div>
</div>
{% include 'info/includes/footer.html' %}
{% endblock %}

templates/schedule/modshift.html
{% extends "info/base.html" %}

{% block title %}
Mod Shift
{% endblock %}

{% block content %}
    {% if usertype == 'Bookeeper' %}
        {% include 'info/includes/book_navbar.html' %}
    {% else %}
        {% include 'info/includes/corr_navbar.html' %}
    {% endif %}
                {% load static %}
       <link rel="stylesheet" href="{% static 'jquery-ui.css' %}" />

      <script src="{% static 'js/jquery-3.6.0.js' %}" ></script>
  <script  src="{% static 'js/jquery-ui-1.13.1.js' %}" ></script>
 <script>
 function changestaff(){
     let words = "";
     words = document.getElementById('staff_search').value;
     let array = words.split(" ");
     let final = array[0].replace(/[()ID]/g,"");
     document.getElementById('id_staff_id').value = final
 }
 </script>
  <script>
  $( function() {
    let availableTags = {{ dropdown | safe }};
    $( "#id_client_id" ).autocomplete({
      source: availableTags
    });
  } );
  </script>
  <script>
  $( function() {
    let availableTags1 = {{ dropdown2 | safe }};
    $( "#staff_search" ).autocomplete({
      source: availableTags1
    });
  } );
  </script>


<!,
      change: function (event, ui) {
          document.getElementById('id_staff_id').value=13;
      }>

<div class='conb'><div class='row justify-content-md-center'><br />




				<form class='form-con' method="post">
                {% csrf_token %}





				<h1>Modify a shift</h1>
                    {% for message in messages %}

    {% if 'error' in message.extra_tags %}
        <div class='alert alert-danger'>{{ message }}</div>
    {% elif 'submit' in message.extra_tags %}
        <div class='alert alert-success'>{{ message }}</div>
    {% endif %}

{% endfor %}
                    {% if overtime == 1 %}
                        <p style="color: orangered">Press the Schedule button to schedule overtime shifts</p>
                        <button name="submit" class='btn btn-primary' type="submit" value="make1">Schedule</button>
                    {% endif %}
                <br>


				 <form class='form-con' method="post">

					<label>Search for Clients:</label>
						{{ form.client_id.errors }}{{ form.client_id }}<br /><br />

					<!--display selection of clients-->


					<!--display selection of departments-->
					Department:
						<select class='fanc' name='dep_code' id="id_dep_code" required="" type="text" class="form-control">
							<option hidden {{ startval }}>{{ startval1 }}</option>
						{% for o in dep %}
                            <option value ="{{ o.dep_code }}">{{ o.dep_name }}</option><br /><br />
                        {% endfor %}
						</select><br /><br />


                     Status:
						<select class='fanc' name='status' id="status" required="" type="text" class="form-control">
							<option hidden {{ status }}>{{ status }}</option>
                            <option value ="Scheduled">Scheduled</option><br /><br />
                            <option value ="Cancelled">Cancelled</option><br /><br />
						</select><br /><br />

					Shift Date:<div class='form-row'><div class='col-12'>
						{{ form.shift_date.errors }}{{ form.shift_date }}<br /><br />

					Start Time:<div class='form-row'><div class='col-12'>
						{{ form.scheduled_start.errors }}{{ form.scheduled_start }}<br /><br />

					</div></div>End Time:<div class='form-row'><div class='col-12'>
						{{ form.scheduled_end.errors }}{{ form.scheduled_end }}<br /><br />

					<!--button to find available staff-->
					</div></div><button formnovalidate name="submit" class='btn btn-primary' type="submit" value="getstaff">View Available Staff</button><br /><br />


                    {% for message in messages %}

    {% if 'mor' in message.extra_tags %}
        <div class='alert alert-danger'>{{ message }}</div>
    {% endif %}

{% endfor %}

					Search for Staff:
                    <input class='form-control' name='staff_search' id='staff_search' onfocus="this.value=''" type="text">
                 <button class="form-control" type="button" onclick="changestaff()">Set staff</button><br /><br />

					<!--display selection of staff members-->
					Staff results:
						<select class='fanc' name='staff_id' id='id_staff_id' type="text" onchange="document.getElementById('staff_search').value = ''" required="">
                            <option hidden {{ staffval }}>{{ staffval1 }}</option>
                            {% for o in dropdown1 %}
                                {% if staffis == 1 %}
                                    <option value ="{{ o.staff_id }}">ID({{ o.staff_id }}) {{ o.staff_fname }}, {{ o.staff_lname }}</option><br /><br />
                                {% else %}
                                    <option value ="{{ o.0 }}">ID({{ o.0 }}) {{ o.1 }}, {{ o.2 }}</option>
                                {% endif %}
                        {% endfor %}
						</select><br /><br />

						is a supervisor:
                    {% if super == 1 %}
					    <input type="checkbox" name="shift_super" value="1" id="id_shift_super" checked=""><br /><br />
                    {% else %}
                         <input type="checkbox" name="shift_super" value="0" id="id_shift_super" unchecked=""><br /><br />
                    {% endif %}
					Shift Notes:<br />
						{{ form.shift_notes.errors }}{{ form.shift_notes }}<br /><br />

					<button name="submit" class='btn btn-primary' type="submit" value="make">Submit</button>
					<a href='/viewshift' class='btn btn-danger'>Cancel</a>

                 </div></form><br />



		</form>
            </div>
</div>
{% include 'info/includes/footer.html' %}
{% endblock %}

templates/schedule/schedshift.html
{% extends "info/base.html" %}

{% block title %}
Schedule Shift
{% endblock %}

{% block content %}
    {% if usertype == 'Bookeeper' %}
        {% include 'info/includes/book_navbar.html' %}
    {% else %}
        {% include 'info/includes/corr_navbar.html' %}
    {% endif %}
                {% load static %}
       <link rel="stylesheet" href="{% static 'jquery-ui.css' %}" />

      <script src="{% static 'js/jquery-3.6.0.js' %}" ></script>
  <script  src="{% static 'js/jquery-ui-1.13.1.js' %}" ></script>
    <script>
function myFunction(the) {
    var but = document.getElementById('id_rec_shift');
  var x = document.getElementById("recs");
  if (but.checked) {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
    if (the == 1) {
        x.style.display = "none";
    }
}
    </script>
 <script>
 function changestaff(){
     let words = "";
     words = document.getElementById('staff_search').value;
     let array = words.split(" ");
     let final = array[0].replace(/[()ID]/g,"");
     document.getElementById('id_staff_id').value = final
 }
 </script>
  <script>
  $( function() {
    let availableTags = {{ dropdown | safe }};
    $( "#id_client_id" ).autocomplete({
      source: availableTags
    });
  } );
  </script>
  <script>
  $( function() {
    let availableTags1 = {{ dropdown2 | safe }};
    $( "#staff_search" ).autocomplete({
      source: availableTags1
    });
  } );
  </script>


<!,
      change: function (event, ui) {
          document.getElementById('id_staff_id').value=13;
      }>

<div class='conb'><div class='row justify-content-md-center'><br />




				<form class='form-con' method="post">
                {% csrf_token %}





				<h1>Schedule a New Shift</h1>
                    {% for message in messages %}

    {% if 'error' in message.extra_tags %}
        <div class='alert alert-danger'>{{ message }}</div>
    {% elif 'submit' in message.extra_tags %}
        <div class='alert alert-success'>{{ message }}</div>
    {% endif %}

{% endfor %}
                    {% if overtime == 1 %}
                        <p style="color: orangered">Press the Schedule button to schedule overtime shifts</p>
                        <button name="submit" class='btn btn-primary' type="submit" value="make1">Schedule</button>
                    {% endif %}
                <br>


				 <form class='form-con' method="post">

					<label>Search for Clients:</label>
						{{ form.client_id.errors }}{{ form.client_id }}<br /><br />

					<!--display selection of clients-->


					<!--display selection of departments-->
					Department:
						<select class='fanc' name='dep_code' id="id_dep_code" required="" type="text" class="form-control">
							<option hidden {{ startval }}>{{ startval1 }}</option>
						{% for o in dep %}
                            <option value ="{{ o.dep_code }}">{{ o.dep_name }}</option><br /><br />
                        {% endfor %}
						</select><br /><br />

					Shift Date:<div class='form-row'><div class='col-12'>
						{{ form.shift_date.errors }}{{ form.shift_date }}<br /><br />

					</div></div>Recurring Shift:{{ form.rec_shift.errors }}{{ form.rec_shift }}<br>

					A recurring shift will repeat once a week on the weekday selected.<br /><br />
                    <div id="recs">
                                            <p>Enter the recurring shift end date</p>
                    {% if enddatte %}
                        <input type="date" name="rec-time" class="form-control" id="rec-time" value={{ enddatte }}><br>
                    {% else %}
                         <input type="date" name="rec-time" class="form-control" id="rec-time" ><br>
                     {% endif %}
                    </div>


					Start Time:<div class='form-row'><div class='col-12'>
						{{ form.scheduled_start.errors }}{{ form.scheduled_start }}<br /><br />

					</div></div>End Time:<div class='form-row'><div class='col-12'>
						{{ form.scheduled_end.errors }}{{ form.scheduled_end }}<br /><br />

					<!--button to find available staff-->
					</div></div><button formnovalidate name="submit" class='btn btn-primary' type="submit" value="getstaff">View Available Staff</button><br /><br />


                    {% for message in messages %}

    {% if 'mor' in message.extra_tags %}
        <div class='alert alert-danger'>{{ message }}</div>
    {% endif %}

{% endfor %}

					Search for Staff:
                    <input class='form-control' name='staff_search' id='staff_search' onfocus="this.value=''" type="text">
                 <button class="form-control" type="button" onclick="changestaff()">Set staff</button><br /><br />

					<!--display selection of staff members-->
					Staff results:
						<select class='fanc' name='staff_id' id='id_staff_id' type="text" onchange="document.getElementById('staff_search').value = ''" required="">
                            <option hidden {{ staffval }}>{{ staffval1 }}</option>
                            {% for o in dropdown1 %}
                                {% if staffis == 1 %}
                                    <option value ="{{ o.staff_id }}">ID({{ o.staff_id }}) {{ o.staff_fname }}, {{ o.staff_lname }}</option><br /><br />
                                {% else %}
                                    <option value ="{{ o.0 }}">ID({{ o.0 }}) {{ o.1 }}, {{ o.2 }}</option>
                                {% endif %}
                        {% endfor %}
						</select><br /><br />

						is a supervisor:
					{{ form.shift_super.errors }}{{ form.shift_super }}<br /><br />

					Shift Notes:<br />
						{{ form.shift_notes.errors }}{{ form.shift_notes }}<br /><br />

					<button name="submit" class='btn btn-primary' type="submit" value="make">Submit</button>
					<a href='/land' class='btn btn-danger'>Cancel</a>

				</form><br />



		</form>
{% if recin %}

{% else %}
    <script>onload=myFunction(0)</script>
{% endif %}
            </div>
</div>
{% include 'info/includes/footer.html' %}
{% endblock %}