Edenbridge2/urls.py
from django.contrib import admin
from django.urls import include, path
import info.views
from register import views as v
from register.views import Passwordviewss
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("info.urls")),
    path('', include("schedule.urls")),
    path('', include("booktime.urls")),
    path('', include("django.contrib.auth.urls")),
    path("addstaff", v.register, name="register"),
    path("changepass/", Passwordviewss.as_view(template_name='info/Staff/changepass.html'), name="register"),
    path("modstaff/<str:pk_test>/", v.modstaff, name="modstaff"),
]

info/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
import register.views
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('land', views.land, name='land'),
    path('land/coordinator', views.cor, name='land-cor'),
    path('land/worker', views.wok, name='land-wok'),
    path('land/bookeeper', views.bok, name='land-bok'),
    path('help', views.help1, name='help'),
    path('about', views.about, name='about'),
    path('viewstaff', views.viewstaff, name='viewstaff'),
    path('addclient', views.addclient, name='addclient'),
    path('viewclient', views.viewclient, name='viewclient'),
    path('modclient/<str:pk_test>/', views.modclient, name='modclient'),
    path('adddep', views.adddep, name='adddep'),
    path('viewdep', views.viewdep, name='viewdep'),
    path('moddep/<str:pk_test>/', views.moddep, name='moddep'),
    path('passuser/<str:pk_test>/', views.changeuserpass, name='passuser'),

]

info/models.py
from django.db import models
from users.models import Profile

# Shift statuses
# Approved
# Claimed
# Scheduled
# Cancelled

# Client,Staff,Group Home, and Department Statuses
# Active
# Inactive
# On Hold

# !!!!!!!!!REMEMBER TO MIGRATE APPS YOU NEED TO DO THEM ONE BY ONE NOT JUST IN GENERAL.


class Client(models.Model):
    client_id = models.AutoField(auto_created=True, db_column='CLIENT_ID', primary_key=True)
    client_status = models.CharField(max_length=14, default="Active", db_column='CLIENT_STATUS')
    client_fname = models.CharField(db_column='CLIENT_FNAME', max_length=20)
    client_lname = models.CharField(db_column='CLIENT_LNAME', max_length=20)
    client_phone = models.CharField(db_column='CLIENT_PHONE', max_length=15, blank=True, null=True)
    client_address = models.CharField(db_column='CLIENT_ADDRESS', max_length=50, blank=True, null=True)
    client_city = models.CharField(db_column='CLIENT_CITY', max_length=20, blank=True, null=True)
    client_max_hours = models.IntegerField(db_column='CLIENT_MAX_HOURS', blank=True, null=True)
    client_km = models.IntegerField(db_column='CLIENT_KM', blank=True, null=True)
    client_notes = models.TextField(db_column='CLIENT_NOTES', blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'client'


class Department(models.Model):
    dep_code = models.CharField(db_column='DEP_CODE', primary_key=True, max_length=3)
    dep_status = models.CharField(max_length=14, default="Active", db_column='DEP_STATUS')
    dep_name = models.CharField(db_column='DEP_NAME', max_length=30, blank=True, null=True)
    dep_desc = models.CharField(db_column='DEP_DESC', max_length=150, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'department'


class RecShift(models.Model):
    rec_id = models.IntegerField(db_column='REC_ID', primary_key=True)
    dep_code = models.ForeignKey(Department, on_delete=models.CASCADE, db_column='DEP_CODE')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, db_column='CLIENT_ID')
    staff = models.ForeignKey(Profile, on_delete=models.CASCADE, db_column='STAFF_ID')
    rec_day = models.CharField(db_column='REC_DAY', max_length=3)
    rec_start = models.TimeField(db_column='REC_START', blank=True, null=True)
    rec_end = models.TimeField(db_column='REC_END', blank=True, null=True)
    rec_super = models.IntegerField(db_column='REC_SUPER', blank=True, null=True)
    rec_notes = models.TextField(db_column='REC_NOTES', blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'rec_shift'


class Shift(models.Model):
    shift_id = models.AutoField(auto_created=True, db_column='SHIFT_ID', primary_key=True)
    rec = models.ForeignKey(RecShift, on_delete=models.CASCADE, db_column='REC_ID', blank=True, null=True)
    status_code = models.CharField(max_length=14, default="Scheduled", db_column='STATUS_CODE')
    dep_code = models.ForeignKey(Department, on_delete=models.CASCADE, db_column='DEP_CODE')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, db_column='CLIENT_ID')
    staff = models.ForeignKey(Profile, on_delete=models.CASCADE, db_column='STAFF_ID')
    shift_date = models.DateField(db_column='SHIFT_DATE')
    scheduled_start = models.TimeField(db_column='SCHEDULED_START', blank=True, null=True)
    scheduled_end = models.TimeField(db_column='SCHEDULED_END', blank=True, null=True)
    claimed_start = models.TimeField(db_column='CLAIMED_START', blank=True, null=True)
    claimed_end = models.TimeField(db_column='CLAIMED_END', blank=True, null=True)
    approved_start = models.TimeField(db_column='APPROVED_START', blank=True, null=True)
    approved_end = models.TimeField(db_column='APPROVED_END', blank=True, null=True)
    shift_super = models.IntegerField(db_column='SHIFT_SUPER', blank=True, null=True)
    shift_notes = models.TextField(db_column='SHIFT_NOTES', blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'shift'

info/views.py
import math
import json
from django.contrib.auth import get_user_model
from .decorators import allowed_users, allowed_users1, auth
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from users.forms import *
from .models import *
from django.http import HttpResponseRedirect, HttpResponse
from users.models import Profile
from django.contrib import messages
from django.core.paginator import Paginator
from .filters import ClientFilter, StaffFilter
from django.http import QueryDict


# redirects from index to the login page or landing page if authenticated.
@login_required
def index(request):
    if request.user.is_authenticated:
        return redirect('/land')
    else:
        return redirect('/login')


# This is the second part of the landing page auth flow where the workers group is verified.
@login_required
@allowed_users(allowed_roles=['Worker'])
def wok(request):
    auth(request)
    return render(request, "info/land_worker.html", {})

@login_required
@allowed_users(allowed_roles=['Coordinator'])
def cor(request):
    auth(request)
    return render(request, "info/land_coordinator.html", {})

@login_required
@allowed_users(allowed_roles=['Bookeeper'])
def bok(request):
    auth(request)
    return render(request, "info/land_bookeeper.html", {})


# This is the first part of the landing page auth flow where the workers group
# is retrived and redirected to the verify page.
@login_required
def land(request):
    auth(request)
    user_group = request.user.groups.values_list('name', flat=True)
    user_group = str(user_group[0])


    if user_group == 'Worker':
        return redirect('land/worker')

    if user_group == 'Supervisor':
        return redirect('land/supervisor')

    if user_group == 'Coordinator':
        return redirect('land/coordinator')

    if user_group == 'Bookeeper':
        return redirect('land/bookeeper')


# this redirects to the right help page, no type auth is used as if the page is leaked no actual data is compromised.

@login_required
def help1(request):

    user_group = request.user.groups.values_list('name', flat=True)
    user_group = str(user_group[0])


    if user_group == 'Worker':
        return render(request, "info/Staff/help/help_worker.html", {'usertype': user_group})

    if user_group == 'Coordinator':
        return render(request, "info/Staff/help/help_coordinator.html", {'usertype': user_group})

    if user_group == 'Bookeeper':
        return render(request, "info/Staff/help/help_bookeeper.html", {'usertype': user_group})


# redirects to the about page.
@login_required
def about(request):
    auth(request)
    return render(request, "info/about.html", {})


# view user entries in the database.
@login_required
@allowed_users(allowed_roles=['Coordinator', 'Bookeeper'])
def viewstaff(request):
    releng = (str(request))
    profile1 = Profile.objects.all()
    user_group = request.user.groups.values_list('name', flat=True)
    user_group = str(user_group[0])

    # sets up paging
    numb = profile1.count()
    numb = math.ceil(numb / 4)
    looper = list(range(1, numb + 1))
    p = Paginator(profile1.order_by('staff_fname'), 4)
    page = request.GET.get('page')
    deppage = p.get_page(page)
    directq = ''
    if "staff_id=" in releng:
        final = releng.split('+')
        final1 = final[0].replace("""<WSGIRequest: GET '/viewstaff?staff_id=ID%28""", '').replace("%29", '')
        query = {'staff_id': str(final1)}
        directq = QueryDict('', mutable=True)
        directq.update(query)
    myFilter = StaffFilter(directq, queryset=Profile.objects.all())
    if "staff_id=" in releng:
        deppage = myFilter.qs
    dropdown_varibles = Profile.objects.all().values_list('staff_id', 'staff_fname', 'staff_lname')
    dropdown = ['Error'] * len(dropdown_varibles)
    counter = 0
    for i in dropdown_varibles:
        dropdown[counter] = 'ID(' + str(i[0]) + ')' + ' ' + i[1] + ', ' + i[2]
        counter += 1
    dropdown = json.dumps(list(dropdown))
    return render(request, 'info/Staff/viewstaff.html', {'profile': profile1, 'usertype': user_group, 'pages': deppage, 'looper': looper, 'dropdown': dropdown, 'myFilter': myFilter})


# Adds a client into the system.
@login_required
@allowed_users(allowed_roles=['Coordinator', 'Bookeeper'])
def addclient(request):

    user_group = request.user.groups.values_list('name', flat=True)
    user_group = str(user_group[0])

    if request.method == "POST":
        form = ClientForm(request.POST)
        if form.is_valid():
            form.full_clean()
            client_fname = form.cleaned_data["client_fname"]
            client_lname = form.cleaned_data["client_lname"]
            client_phone = form.cleaned_data["client_phone"]
            client_address = form.cleaned_data["client_address"]
            client_city = form.cleaned_data["client_city"]
            client_max_hours = form.cleaned_data["client_max_hours"]
            client_km = form.cleaned_data["client_km"]
            client_notes = form.cleaned_data["client_notes"]
            t = Client(client_fname=client_fname, client_lname=client_lname, client_phone=client_phone,
                       client_address=client_address, client_city=client_city, client_max_hours=client_max_hours,
                       client_km=client_km, client_notes=client_notes, client_status='Active')
            t.save()
        if form.is_valid():
            messages.success(request, f'Added Client: {client_fname}, {client_lname} Sucsessfully')
            return HttpResponseRedirect('/addclient')
        else:
            form = ClientForm()
            return render(request, 'info/Client/addclient.html', {'form': form, 'usertype': user_group})

    else:
        form = ClientForm()
        return render(request, 'info/Client/addclient.html', {'form': form, 'usertype': user_group})


# Allows the viewing of clients in the database.
@login_required
@allowed_users(allowed_roles=['Coordinator', 'Bookeeper'])
def viewclient(request):
    releng = (str(request))
    client = Client.objects.all()
    user_group = request.user.groups.values_list('name', flat=True)
    user_group = str(user_group[0])
    numb = client.count()
    numb = math.ceil(numb / 4)
    looper = list(range(1, numb + 1))
    p = Paginator(client.order_by('client_fname'), 4)
    page = request.GET.get('page')
    deppage = p.get_page(page)
    directq = ''
    if "client_id=" in releng:
        final = releng.split('+')
        final1 = final[0].replace("""<WSGIRequest: GET '/viewclient?client_id=CID%28""", '').replace("%29", '')
        query = {'client_id': str(final1)}
        directq = QueryDict('', mutable=True)
        directq.update(query)
    myFilter = ClientFilter(directq, queryset=Client.objects.all())
    if "client_id=" in releng:
        deppage = myFilter.qs
    dropdown_varibles = Client.objects.all().values_list('client_id', 'client_fname', 'client_lname')
    dropdown = ['Error'] * len(dropdown_varibles)
    counter = 0
    for i in dropdown_varibles:
        dropdown[counter] = 'CID(' + str(i[0]) + ')' + ' ' + i[1] + ', ' + i[2]
        counter += 1
    dropdown = json.dumps(list(dropdown))
    return render(request, 'info/Client/viewclient.html', {'client': client, 'usertype': user_group, 'pages': deppage, 'looper': looper, "myFilter": myFilter, 'dropdown': dropdown})


# Allows the modification of clients already in the database.
@login_required
@allowed_users1(allowed_roles=['Coordinator', 'Bookeeper'])
def modclient(request):
    user_group = request.user.groups.values_list('name', flat=True)
    user_group = str(user_group[0])

    test = str(request)
    y = ''
    for x in test:
        if x.isnumeric():
            y = y + x

    clientinfo = Client.objects.filter(client_id=y)
    if request.method == "POST":
        form = ClientForm(request.POST)
        if form.is_valid():
            form.full_clean()
            client_fname = form.cleaned_data["client_fname"]
            client_status = form.cleaned_data["client_status"]
            client_lname = form.cleaned_data["client_lname"]
            client_phone = form.cleaned_data["client_phone"]
            client_address = form.cleaned_data["client_address"]
            client_city = form.cleaned_data["client_city"]
            client_max_hours = form.cleaned_data["client_max_hours"]
            client_km = form.cleaned_data["client_km"]
            client_notes = form.cleaned_data["client_notes"]

            Client.objects.filter(pk=y).update(client_fname=client_fname, client_lname=client_lname,
                                               client_phone=client_phone, client_address=client_address,
                                               client_city=client_city, client_max_hours=client_max_hours,
                                               client_km=client_km, client_notes=client_notes,
                                               client_status=client_status)
        if form.is_valid():
            messages.success(request, f'Modded Client {client_fname}, {client_lname} Sucsessfully')
            return HttpResponseRedirect('/viewclient')
        else:
            for i in clientinfo:
                form = ClientForm(
                    initial={'client_fname': i.client_fname, 'client_lname': i.client_lname,
                             'client_phone': i.client_phone,
                             'client_address': i.client_address, 'client_city': i.client_city,
                             'client_max_hours': i.client_max_hours,
                             'client_km': i.client_km, 'client_notes': i.client_notes, 'client_status': i.client_status,
                             'gh_id': i.client_fname})
                return render(request, 'info/Client/modclient.html',
                              {'getid': i.gh_id, 'clientinfo': clientinfo, 'usergroup': user_group,
                               'form': form, 'usertype': user_group})

templates/info/Client/addclient.html
{% extends "info/base.html" %}

{% block title %}
Add Client
{% endblock %}

{% block content %}
    {% if usertype == 'Bookeeper' %}
        {% include 'info/includes/book_navbar.html' %}
    {% else %}
        {% include 'info/includes/corr_navbar.html' %}
    {% endif %}
    <div class="conb">
    <div class="row justify-content-sm-center">
        <form class='form-con' method="post">

            {% csrf_token %}
            {% if messages %}
            {% for message in messages %}
            <div class='alert alert-success'>{{ message }}</div>
            {% endfor %}
            {% endif %}
            <h1>Add New Client</h1>
                First Name:
                        {{ form.client_fname.errors }}{{ form.client_fname }}
                    Last Name:
                         {{ form.client_lname.errors }}{{ form.client_lname }}<br /><br />
                    Full Address:
                        {{ form.client_address.errors }}{{ form.client_address }}
                    City:
                         {{ form.client_city.errors }}{{ form.client_city }}<br /><br />
                    Phone Number:<div class='form-row'><div class='col-12'>
                         {{ form.client_phone.errors }}{{ form.client_phone }}<br />
                        <p class='text-danger'>Format: 000-000-0000</p>

                    Hours Per Month:<div class='form-row'><div class='col-12'>
                        {{ form.client_max_hours.errors }}{{ form.client_max_hours }}<br /><br /><br />
                    </div></div>Distance (in kilometers):<div class='form-row'><div class='col-12'>
                        {{ form.client_km.errors }}{{ form.client_km }}
                    </div></div>Notes:<br />
                          {{ form.client_notes.errors }}{{ form.client_notes }}<br /><br />

					<button class='btn btn-primary' type="submit">Submit</button>

					<a href='/land' class='btn btn-danger'>Cancel</a>

        </div></div></form></div></div><br />
        {% include 'info/includes/footer.html' %}
{% endblock %}

templates/info/Client/modclient.html
{% extends "info/base.html" %}

{% block title %}
Mod Client
{% endblock %}

{% block content %}
    {% if usertype == 'Bookeeper' %}
        {% include 'info/includes/book_navbar.html' %}
    {% else %}
        {% include 'info/includes/corr_navbar.html' %}
    {% endif %}
    <div class="conb">
    <div class="row justify-content-sm-center">
    <form class='form-con' method="post">
				<h1>Modify a Client</h1>
                    {% csrf_token %}
                    {% for i in clientinfo %}
					<input class='form-fan' type='hidden' name='id' value='$id'>
					First Name:
						{{ form.client_fname.errors }}{{ form.client_fname }}
					Last Name:
						{{ form.client_lname.errors }}{{ form.client_lname }}<br /><br />

					Full Address:
						{{ form.client_address.errors }}{{ form.client_address }}
					City:
						{{ form.client_city.errors }}{{ form.client_city }}<br /><br />

						Primary Phone Number:
						<input {{ phone }}><br />
						<p class='text-danger'>Format: 000-000-0000</p>

					<!--display selection of statuses-->
					Status:
						{{ form.client_status.errors }}{{ form.client_status }}<br /><br />

					<!--display selection of group homes-->
					<br>Distance (in kilometers):<div class='form-row'><div class='col-12'>
						{{ form.client_km.errors }}{{ form.client_km }}<br /><br />

					</div></div>Max Hours per Month:<div class='form-row'><div class='col-12'>
						{{ form.client_max_hours.errors }}{{ form.client_max_hours }}<br /><br />

					</div></div>Notes:<br />
						{{ form.client_notes.errors }}{{ form.client_notes }}<br /><br />
                    {% endfor %}
					<button class='btn btn-primary' type="submit">Submit</button>
					<a href='/viewclient' class='btn btn-danger'>Cancel</a>

    </form></div></div><br />

				<!--cancel button that returns user to previous page-->
{% include 'info/includes/footer.html' %}
{% endblock %}>

templates/info/Client/viewclient.html
{% extends "info/base.html" %}
{% block title %}
View Client
{% endblock %}

{% block content %}
            {% load static %}
       <link rel="stylesheet" href="{% static 'jquery-ui.css' %}" />

      <script src="{% static 'js/jquery-3.6.0.js' %}" ></script>
  <script  src="{% static 'js/jquery-ui-1.13.1.js' %}" ></script>
  <script>
  $( function() {
    let availableTags = {{ dropdown | safe }};
    $( "#id_client_lname" ).autocomplete({
      source: availableTags
    });
  } );
  </script>
    {% if usertype == 'Bookeeper' %}
        {% include 'info/includes/book_navbar.html' %}
    {% else %}
        {% include 'info/includes/corr_navbar.html' %}
    {% endif %}
    <div class="conb">
	<div class="row justify-content-center">

        <div class="form-con">
        {% if messages %}
            {% for message in messages %}
            <div class='alert alert-success'>{{ message }}</div>
            {% endfor %}
            {% endif %}
        <form method="get">
            <label>Search for a client:</label>
        <input type="text" name="client_id" id="id_client_lname" class="ui-autocomplete-input" autocomplete="off"> <button class='btn btn-primary' type="submit">Submit</button><a href='/viewclient' class='btn btn-info'>All Clients</a>
        <br><br>
        </form>
        <table border='1'>
				<tr>
					<th>
						<button style='background: none;
										border: none;
										padding: 0;
										color: white;
										font-weight: bold;
										text-decoration: none;
										cursor: pointer;' type='submit' form='clientForm' value='client'>Client
						</button>
					</th>
					<th>
						<button style='background: none;
										border: none;
										padding: 0;
										color: white;
										font-weight: bold;
										text-decoration: none;
										cursor: pointer;' type='submit' form='statForm' value='status'>Status
						</button>
					</th>
					<th>Phone Number</th>
					<th>Address</th>
					<th>
						<button style='background: none;
										border: none;
										padding: 0;
										color: white;
										font-weight: bold;
										text-decoration: none;
										cursor: pointer;' type='submit' form='cityForm' value='city'>City
						</button>
					</th>
					<th>
						<button style='background: none;
										border: none;
										padding: 0;
										color: white;
										font-weight: bold;
										text-decoration: none;
										cursor: pointer;' type='submit' form='hourForm' value='hours'>Max Hours per Month
						</button>
					</th>
					<th>
						<button style='background: none;
										border: none;
										padding: 0;
										color: white;
										font-weight: bold;
										text-decoration: none;
										cursor: pointer;' type='submit' form='distForm' value='dist'>Distance (KM)
						</button>
					</th>
					<th>Notes</th>
					<th></th>
				</tr>
			
			

			    {% for i in pages %}
				<tr>
				<td>CID({{ i.client_id }}) {{ i.client_fname }}, {{ i.client_lname }}</td>
				<td>{{ i.client_status }}</td>
				<td>{{ i.client_phone }}</td>
				<td>{{ i.client_address }}</td>
				<td>{{ i.client_city }}</td>
				<td>{{ i.client_max_hours }}</td>
				<td>{{ i.client_km }}</td>
				<td style='width: 17%;'><div class ='scro'><textarea class ='scro'>{{ i.client_notes }}</textarea></div></td>
				<td><a href='modclient/{{ i.client_id }}'class='btn btn-info'>modify</a></td>
				</tr>

			{% endfor %}
        </table><br>


        <span class="badge bg-primary">
			 <h3>Page:{{ pages.number }}
			 </h3><ul class="pagination">
                {% if pages.has_previous == True %}
                    <a href="?page=1" class='page-link'>First</a>
                <a href="?page={{ pages.previous_page_number }}" class='page-link'>Previous</a>
                {% endif %}


                 {% for i in looper %}
                    <a href="?page={{ i }}" class='page-link'>{{ i }}</a>
                 {% endfor %}

            {% if pages.has_next == True %}
                 <a href="?page={{ pages.next_page_number }}" class='page-link'>Next</a>
                 <a href="?page={{ pages.paginator.num_pages }}" class='page-link'>Last</a>
            {% endif %}


		   <div class="dropdown">
			<button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">Skip To <span class="caret"></span></button>
			<ul class="dropdown-menu scrollable-menu" role="menu">

                {% for w in looper %}
				<li><a class='dropdown-item' href='?page={{ w }}'>Page:{{ w }}</a></li>
                {% endfor %}
            </ul>
		  </div>


			 <a href='/land' class='btn btn-info'>Back</a>
            </ul></span></div></div></div></span>



        </div></div></div><br />

        {% include 'info/includes/footer.html' %}


{% endblock %}