Edenbridge2/urls.py
from django.contrib import admin
from django.urls import include, path
import info.views
from register import views as v
from register.views import Passwordviewss
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("info.urls")),
    path('', include("schedule.urls")),
    path('', include("booktime.urls")),
    path('', include("django.contrib.auth.urls")),
    path("addstaff", v.register, name="register"),
    path("changepass/", Passwordviewss.as_view(template_name='info/Staff/changepass.html'), name="register"),
    path("modstaff/<str:pk_test>/", v.modstaff, name="modstaff"),
]

info/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
import register.views
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('land', views.land, name='land'),
    path('land/coordinator', views.cor, name='land-cor'),
    path('land/worker', views.wok, name='land-wok'),
    path('land/bookeeper', views.bok, name='land-bok'),
    path('help', views.help1, name='help'),
    path('about', views.about, name='about'),
    path('viewstaff', views.viewstaff, name='viewstaff'),
    path('addclient', views.addclient, name='addclient'),
    path('viewclient', views.viewclient, name='viewclient'),
    path('modclient/<str:pk_test>/', views.modclient, name='modclient'),
    path('adddep', views.adddep, name='adddep'),
    path('viewdep', views.viewdep, name='viewdep'),
    path('moddep/<str:pk_test>/', views.moddep, name='moddep'),
    path('passuser/<str:pk_test>/', views.changeuserpass, name='passuser'),

]

users/forms.py
from django import forms
from django.forms import ModelForm


type1 = (
    ("Active", "Active"),
    ("On Hold", "On Hold"),
    ("Inactive", "Inactive"),
)

type2 = (
    ("7", "N/A"),
)


class ClientForm(forms.Form):
    client_status = forms.ChoiceField(required=False, choices=type1)
    client_fname = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    client_lname = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    client_phone = forms.CharField(required=True, max_length=13, widget=forms.TextInput(attrs={'class': 'form-control'}))
    client_address = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    client_city = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    client_max_hours = forms.IntegerField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    client_km = forms.IntegerField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    client_notes = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control'}))
    gh_id = forms.CharField(required=False)


class Departmentform(forms.Form):
    dep_code = forms.CharField(required=False, max_length=3, widget=forms.TextInput(attrs={'class': 'form-control'}))
    gh_id = forms.CharField
    dep_status = forms.ChoiceField(required=False, choices=type1)
    dep_name = forms.CharField(required=True, max_length=40, widget=forms.TextInput(attrs={'class': 'form-control'}))
    dep_desc = forms.CharField(required=False, max_length=1500, widget=forms.Textarea(attrs={'class': 'form-control'}))


class GroupHomeform(forms.Form):
    staff_id = forms.CharField(required=False)
    gh_status = forms.ChoiceField(required=False, choices=type1)
    gh_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    gh_phone = forms.CharField(required=False, max_length=13, widget=forms.TextInput(attrs={'class': 'form-control'}))
    gh_address = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    gh_city = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))


class AdminPassChange(forms.Form):
    password1 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

info/views.py
import math
import json
from django.contrib.auth import get_user_model
from .decorators import allowed_users, allowed_users1, auth
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from users.forms import *
from .models import *
from django.http import HttpResponseRedirect, HttpResponse
from users.models import Profile
from django.contrib import messages
from django.core.paginator import Paginator
from .filters import ClientFilter, StaffFilter
from django.http import QueryDict


# redirects from index to the login page or landing page if authenticated.
@login_required
def index(request):
    if request.user.is_authenticated:
        return redirect('/land')
    else:
        return redirect('/login')


# This is the second part of the landing page auth flow where the workers group is verified.
@login_required
@allowed_users(allowed_roles=['Worker'])
def wok(request):
    auth(request)
    return render(request, "info/land_worker.html", {})

@login_required
@allowed_users(allowed_roles=['Coordinator'])
def cor(request):
    auth(request)
    return render(request, "info/land_coordinator.html", {})

@login_required
@allowed_users(allowed_roles=['Bookeeper'])
def bok(request):
    auth(request)
    return render(request, "info/land_bookeeper.html", {})


# This is the first part of the landing page auth flow where the workers group
# is retrived and redirected to the verify page.
@login_required
def land(request):
    auth(request)
    user_group = request.user.groups.values_list('name', flat=True)
    user_group = str(user_group[0])


    if user_group == 'Worker':
        return redirect('land/worker')

    if user_group == 'Supervisor':
        return redirect('land/supervisor')

    if user_group == 'Coordinator':
        return redirect('land/coordinator')

    if user_group == 'Bookeeper':
        return redirect('land/bookeeper')


# this redirects to the right help page, no type auth is used as if the page is leaked no actual data is compromised.

@login_required
def help1(request):

    user_group = request.user.groups.values_list('name', flat=True)
    user_group = str(user_group[0])


    if user_group == 'Worker':
        return render(request, "info/Staff/help/help_worker.html", {'usertype': user_group})

    if user_group == 'Coordinator':
        return render(request, "info/Staff/help/help_coordinator.html", {'usertype': user_group})

    if user_group == 'Bookeeper':
        return render(request, "info/Staff/help/help_bookeeper.html", {'usertype': user_group})


# redirects to the about page.
@login_required
def about(request):
    auth(request)
    return render(request, "info/about.html", {})


# view user entries in the database.
@login_required
@allowed_users(allowed_roles=['Coordinator', 'Bookeeper'])
def viewstaff(request):
    releng = (str(request))
    profile1 = Profile.objects.all()
    user_group = request.user.groups.values_list('name', flat=True)
    user_group = str(user_group[0])

    # sets up paging
    numb = profile1.count()
    numb = math.ceil(numb / 4)
    looper = list(range(1, numb + 1))
    p = Paginator(profile1.order_by('staff_fname'), 4)
    page = request.GET.get('page')
    deppage = p.get_page(page)
    directq = ''
    if "staff_id=" in releng:
        final = releng.split('+')
        final1 = final[0].replace("""<WSGIRequest: GET '/viewstaff?staff_id=ID%28""", '').replace("%29", '')
        query = {'staff_id': str(final1)}
        directq = QueryDict('', mutable=True)
        directq.update(query)
    myFilter = StaffFilter(directq, queryset=Profile.objects.all())
    if "staff_id=" in releng:
        deppage = myFilter.qs
    dropdown_varibles = Profile.objects.all().values_list('staff_id', 'staff_fname', 'staff_lname')
    dropdown = ['Error'] * len(dropdown_varibles)
    counter = 0
    for i in dropdown_varibles:
        dropdown[counter] = 'ID(' + str(i[0]) + ')' + ' ' + i[1] + ', ' + i[2]
        counter += 1
    dropdown = json.dumps(list(dropdown))
    return render(request, 'info/Staff/viewstaff.html', {'profile': profile1, 'usertype': user_group, 'pages': deppage, 'looper': looper, 'dropdown': dropdown, 'myFilter': myFilter})


# Adds a client into the system.
@login_required
@allowed_users(allowed_roles=['Coordinator', 'Bookeeper'])
def addclient(request):

    user_group = request.user.groups.values_list('name', flat=True)
    user_group = str(user_group[0])

    if request.method == "POST":
        form = ClientForm(request.POST)
        if form.is_valid():
            form.full_clean()
            client_fname = form.cleaned_data["client_fname"]
            client_lname = form.cleaned_data["client_lname"]
            client_phone = form.cleaned_data["client_phone"]
            client_address = form.cleaned_data["client_address"]
            client_city = form.cleaned_data["client_city"]
            client_max_hours = form.cleaned_data["client_max_hours"]
            client_km = form.cleaned_data["client_km"]
            client_notes = form.cleaned_data["client_notes"]
            t = Client(client_fname=client_fname, client_lname=client_lname, client_phone=client_phone,
                       client_address=client_address, client_city=client_city, client_max_hours=client_max_hours,
                       client_km=client_km, client_notes=client_notes, client_status='Active')
            t.save()
        if form.is_valid():
            messages.success(request, f'Added Client: {client_fname}, {client_lname} Sucsessfully')
            return HttpResponseRedirect('/addclient')
        else:
            form = ClientForm()
            return render(request, 'info/Client/addclient.html', {'form': form, 'usertype': user_group})

    else:
        form = ClientForm()
        return render(request, 'info/Client/addclient.html', {'form': form, 'usertype': user_group})


# Allows the viewing of clients in the database.
@login_required
@allowed_users(allowed_roles=['Coordinator', 'Bookeeper'])
def viewclient(request):
    releng = (str(request))
    client = Client.objects.all()
    user_group = request.user.groups.values_list('name', flat=True)
    user_group = str(user_group[0])
    numb = client.count()
    numb = math.ceil(numb / 4)
    looper = list(range(1, numb + 1))
    p = Paginator(client.order_by('client_fname'), 4)
    page = request.GET.get('page')
    deppage = p.get_page(page)
    directq = ''
    if "client_id=" in releng:
        final = releng.split('+')
        final1 = final[0].replace("""<WSGIRequest: GET '/viewclient?client_id=CID%28""", '').replace("%29", '')
        query = {'client_id': str(final1)}
        directq = QueryDict('', mutable=True)
        directq.update(query)
    myFilter = ClientFilter(directq, queryset=Client.objects.all())
    if "client_id=" in releng:
        deppage = myFilter.qs
    dropdown_varibles = Client.objects.all().values_list('client_id', 'client_fname', 'client_lname')
    dropdown = ['Error'] * len(dropdown_varibles)
    counter = 0
    for i in dropdown_varibles:
        dropdown[counter] = 'CID(' + str(i[0]) + ')' + ' ' + i[1] + ', ' + i[2]
        counter += 1
    dropdown = json.dumps(list(dropdown))
    return render(request, 'info/Client/viewclient.html', {'client': client, 'usertype': user_group, 'pages': deppage, 'looper': looper, "myFilter": myFilter, 'dropdown': dropdown})


# Allows the modification of clients already in the database.
@login_required
@allowed_users1(allowed_roles=['Coordinator', 'Bookeeper'])
def modclient(request):
    user_group = request.user.groups.values_list('name', flat=True)
    user_group = str(user_group[0])

    test = str(request)
    y = ''
    for x in test:
        if x.isnumeric():
            y = y + x

    clientinfo = Client.objects.filter(client_id=y)
    if request.method == "POST":
        form = ClientForm(request.POST)
        if form.is_valid():
            form.full_clean()
            client_fname = form.cleaned_data["client_fname"]
            client_status = form.cleaned_data["client_status"]
            client_lname = form.cleaned_data["client_lname"]
            client_phone = form.cleaned_data["client_phone"]
            client_address = form.cleaned_data["client_address"]
            client_city = form.cleaned_data["client_city"]
            client_max_hours = form.cleaned_data["client_max_hours"]
            client_km = form.cleaned_data["client_km"]
            client_notes = form.cleaned_data["client_notes"]

            Client.objects.filter(pk=y).update(client_fname=client_fname, client_lname=client_lname,
                                               client_phone=client_phone, client_address=client_address,
                                               client_city=client_city, client_max_hours=client_max_hours,
                                               client_km=client_km, client_notes=client_notes,
                                               client_status=client_status)
        if form.is_valid():
            messages.success(request, f'Modded Client {client_fname}, {client_lname} Sucsessfully')
            return HttpResponseRedirect('/viewclient')
        else:
            for i in clientinfo:
                form = ClientForm(
                    initial={'client_fname': i.client_fname, 'client_lname': i.client_lname,
                             'client_phone': i.client_phone,
                             'client_address': i.client_address, 'client_city': i.client_city,
                             'client_max_hours': i.client_max_hours,
                             'client_km': i.client_km, 'client_notes': i.client_notes, 'client_status': i.client_status,
                             'gh_id': i.client_fname})
                return render(request, 'info/Client/modclient.html',
                              {'getid': i.gh_id, 'clientinfo': clientinfo, 'usergroup': user_group,
                               'form': form, 'usertype': user_group})

templates/info/Staff/addstaff.html
{% extends "info/base.html" %}

{% block title %}
Add Staff
{% endblock %}

{% block content %}

{% endblock %}

templates/info/Staff/cahngestaffpass.html
{% extends "info/base.html" %}

{% block title %}
Change Staff Password
{% endblock %}

{% block content %}


                <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-primary">
					<a class="navbar-brand" href="/land">
                        {% load static %}
						<img src="{% static 'images/Logo.png' %}" width="60" height="30" class="d-inline-block align-top" alt="">
						Edenbridge Employee Portal
					</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>

				</nav>
    		<div class="conb">
			<div class="row justify-content-sm-center">

				<form class="form-con" method="POST">
				<h1>Change Users Password</h1><br />

                    {% csrf_token %}
                    <hi>New Password:</hi>
                     {{ form.password1.errors }}{{ form.password1 }}
                    <br>
                    <br>
                    <hi>Confrim Password:</hi>
                     {{ form.password2.errors }}{{ form.password2 }}
                    <br>
                    <br>
                    <ul>
                        <li>Your password can’t be too similar to your other personal information.<li>
                        <li>Your password must contain at least 8 characters.</li>
                        <li>Your password can’t be a commonly used password.</li>
                        <li>Your password can’t be entirely numeric.</li>
                    </ul>

					 <button class="btn btn-primary">Submit</button>
									<a href='/viewstaff' class='btn btn-danger'>Cancel</a>

				</form>





	</div>
</div>

{% endblock %}

templates/info/Staff/changepass.html
{% extends "info/base.html" %}

{% block title %}
Change Password
{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-primary">
					<a class="navbar-brand" href="/land">
                        {% load static %}
						<img src="{% static 'images/Logo.png' %}" width="120" height="30" class="d-inline-block align-top" alt="">Portal
					</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>

				</nav>
    		<div class="conb">
			<div class="row justify-content-sm-center">

				<form class="form-con" method="POST">
				<h1>Change Password</h1><br />

                    {% csrf_token %}
                    <p>
    <label for="id_old_password">Old password:</label>
    <input class="form-control" type="password" name="old_password" autocomplete="current-password" autofocus="" required="" id="id_old_password">


  </p>
                    <p>
    <label for="id_new_password1">New password:</label>
    <input class="form-control" type="password" name="new_password1" autocomplete="new-password" required="" id="id_new_password1">
                        <p>
    <label for="id_new_password2">New password confirmation:</label>
    <input class="form-control" type="password" name="new_password2" autocomplete="new-password" required="" id="id_new_password2">
<ul><li>Your password can’t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can’t be a commonly used password.</li><li>Your password can’t be entirely numeric.</li></ul>



  </p>

      <span class="helptext"></span></p>



					 <button class="btn btn-primary">Submit</button>
									<a href='/land' class='btn btn-danger'>Cancel</a>

				</form>





	</div>
</div>
{% endblock %}

templates/info/Staff/modstaff.html
{% extends "info/base.html" %}

{% block title %}
Mod Staff
{% endblock %}

{% block content %}
    {% if usertype == 'Bookeeper' %}
        {% include 'info/includes/book_navbar.html' %}
    {% else %}
        {% include 'info/includes/corr_navbar.html' %}
    {% endif %}
                            <script>
function myFunction(the) {
  var x = document.getElementById("myDIV");
  if (the == 1) {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}
</script>
    <style>

    body{
        font-weight: 399;
    }

    </style>

    <div class="conb">
			<div class="row justify-content-sm-center">



				<form class='form-con' method="post">
                    {% csrf_token %}
				<h1>Modify a Staff Member</h1>
                                        {% for message in messages %}

    {% if 'error' in message.extra_tags %}
        <div class='alert alert-danger'>{{ message }}</div>
    {% elif 'submit' in message.extra_tags %}
        <div class='alert alert-success'>{{ message }}</div>
    {% endif %}

{% endfor %}

					<input class='form-fan' type='hidden' name='id' value='id'>
					First Name:
						{{ form1.Firstname.errors }}{{ form1.Firstname }}
					Last Name:
						{{ form1.Lastname.errors }}{{ form1.Lastname }}<br /><br />

					Full Address:
						{{ form1.Fulladdress.errors }}{{ form1.Fulladdress }}
					City:
						{{ form1.City.errors }}{{ form1.City }}<br /><br />

					Primary Phone Number:
						<input {{ phone }}><br />
						<p class='text-danger'>Format: 000-000-0000</p>

					<!--display selection of statuses-->
					Status:
					<select name="status" id="typer">
                                <option value='{{ stat }}' hidden>{{ stat }}</option>
                                <option value="Active">Active</option>
                                <option value="On Hold">On Hold</option>
                                <option value="Inactive">Inactive</option>

                                </select>

			            <br /><br />

					<!--display selection of user types-->
						User Type:  <select name="type" id="cars">
                                <option value='{{ tyype }}' hidden>{{ tyype }}</option>
                                <option value="Worker" onclick="myFunction(1)" >Worker</option>
                                <option value="Coordinator" onclick="myFunction(0)">Coordinator</option>
                                <option value="Bookeeper" onclick="myFunction(0)">Bookeeper</option>
                                </select>

			            <br /><br />

					User Name:<div class='form-row'><div class='col-12'>
						<input class='form-fan' type='text' name='uname' value='{{ unamev }}'><br /><br />
					</div></div>Change Password:<br />
                    <a href='/passuser/{{ idf }}/' class='btn btn-info'>Change Password</a><br>

                    <div id="myDIV">
                            Availability: <br /><br />
							Sunday:
								Start:
									<input class='form-fan' type='time' name='sunSt' value='{{ sunSt }}'>
								End:
									<input class='form-fan' type='time' name='sunEnd' value='{{ sunEnd }}'><br /><br />
							Monday:
								Start:
									<input class='form-fan' type='time' name='monSt' value='{{ monSt }}'>
								End:
									<input class='form-fan' type='time' name='monEnd' value='{{ monEnd }}'><br /><br />

							Tuesday:
								Start:
									<input class='form-fan' type='time' name='tueSt' value='{{ tueSt }}'>
								End:
									<input class='form-fan' type='time' name='tueEnd' value='{{ tueEnd }}'><br /><br />

							 Wednesday:
								Start:
									<input class='form-fan' type='time' name='wedSt' value='{{ wedSt }}'>
								End:
									<input class='form-fan' type='time' name='wedEnd' value='{{ wedEnd }}'><br /><br />

							 Thursday:
								Start:
									<input class='form-fan' type='time' name='thuSt' value='{{ thuSt }}'>
								End:
									<input class='form-fan' type='time' name='thuEnd' value='{{ thuEnd }}'><br /><br />

							 Friday:
								Start:
									<input class='form-fan' type='time' name='friSt' value='{{ friSt }}'>
								End:
									<input class='form-fan' type='time' name='friEnd' value='{{ friEnd }}'><br /><br />

							 Saturday:
								Start:
									<input class='form-fan' type='time' name='satSt' value='{{ satSt }}'>
								End:
									<input class='form-fan' type='time' name='satEnd' value='{{ satEnd }}'><br /><br />



                        </div>

					Notes:<br />
						{{ form1.Notes.errors }}{{ form1.Notes }}<br /><br />

					<button class='btn btn-primary' type="submit">Submit</button>					<a href='/viewstaff' class='btn btn-danger'>Cancel</a>
				</form>
                <script>onload=myFunction({{ graph }})</script>
				<!--cancel button that returns user to previous page-->

            </div></div>

    {% include 'info/includes/footer.html' %}
{% endblock %}

templates/info/Staff/viewstaff.html
{% extends "info/base.html" %}

{% block title %}
View Staff
{% endblock %}

{% block content %}
                {% load static %}
       <link rel="stylesheet" href="{% static 'jquery-ui.css' %}" />

      <script src="{% static 'js/jquery-3.6.0.js' %}" ></script>
  <script  src="{% static 'js/jquery-ui-1.13.1.js' %}" ></script>
  <script>
  $( function() {
    var availableTags = {{ dropdown | safe }};
    $( "#id_staff_id" ).autocomplete({
      source: availableTags
    });
  } );
  </script>
    {% if usertype == 'Bookeeper' %}
        {% include 'info/includes/book_navbar.html' %}
    {% else %}
        {% include 'info/includes/corr_navbar.html' %}
    {% endif %}
    <div>
    <div class="conb" style="width: 95%;">
	<div class="row justify-content-center">
    <div class="form-con">
     <form method="get">
                      {% if messages %}
            {% for message in messages %}
            <div class='alert alert-success'>{{ message }}</div>
            {% endfor %}
            {% endif %}
         <label>Search for staff:</label>
        <input type="text" name="staff_id" step="any" id="id_staff_id"> <button class='btn btn-primary' type="submit">Submit</button><a href='/viewstaff' class='btn btn-info'>All Staff</a>
        <br><br>
        </form>
			<table class='table-sm' border='1'>
                <tr>
					<th>Staff</th>
					<th>Status</th>
					<th>Staff Type</th>
					<th>Username</th>
					<th>Phone Number</th>
					<th>Address</th>
					<th>City</th>
					<th>Sunday Availability:</th>
					<th>Monday Availability:</th>
					<th>Tuesday Availability:</th>
					<th>Wednesday Availability:</th>
					<th>Thursday Availability:</th>
					<th>Friday Availability:</th>
					<th>Saturday Availability:</th>
					<th>Notes</th>
					<th></th>
				</tr>
                {% for i in pages %}
                    <tr>
                    <td> ID({{ i.staff_id }}) {{ i.staff_fname }}, {{ i.staff_lname }}</td>
				    <td>{{ i.staff_status }}</td>
				    <td>{{ i.type_code }}</td>
				    <td>{{ i.user }}</td>
				    <td style='min-width: 110px;'>{{ i.staff_phone }}</td>
				    <td style='min-width: 135px;'>{{ i.staff_address }}</td>
				    <td>{{ i.staff_city }}</td>
				    <td>{{ i.sun_avail }}</td>
				    <td>{{ i.mon_avail }}</td>
				    <td>{{ i.tue_avail }}</td>
				    <td>{{ i.wed_avail }}</td>
				    <td>{{ i.thu_avail }}</td>
				    <td>{{ i.fri_avail }}</td>
				    <td>{{ i.sat_avail }}</td>
				    <td style='width: 110%;'> <div class ='scro'> <textarea class ='scro'>{{ i.staff_notes }}</textarea>
                    </div></td>
				    <td><a href='modstaff/{{ i.staff_id }}/' class='btn btn-info'>modify</a></td>
				    </tr>
                {% endfor %}


			</table><br/>
     <span class="badge bg-primary">
			 <h3>Page:{{ pages.number }}
			 </h3><ul class="pagination">
                {% if pages.has_previous == True %}
                    <a href="?page=1" class='page-link'>First</a>
                <a href="?page={{ pages.previous_page_number }}" class='page-link'>Previous</a>
                {% endif %}


                 {% for i in looper %}
                    <a href="?page={{ i }}" class='page-link'>{{ i }}</a>
                 {% endfor %}

            {% if pages.has_next == True %}
                 <a href="?page={{ pages.next_page_number }}" class='page-link'>Next</a>
                 <a href="?page={{ pages.paginator.num_pages }}" class='page-link'>Last</a>
            {% endif %}


		   <div class="dropdown">
			<button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">Skip To <span class="caret"></span></button>
			<ul class="dropdown-menu scrollable-menu" role="menu">

                {% for w in looper %}
				<li><a class='dropdown-item' href='?page={{ w }}'>Page:{{ w }}</a></li>
                {% endfor %}
            </ul>
		  </div>


			 <a href='/land' class='btn btn-info'>Back</a>
            </ul></span> {% include 'info/includes/footer.html' %}</div></div></div></div></span></div>

{% endblock %}